In [1]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import statsmodels.formula.api as smf
import scipy.stats as stats
import seaborn as sns
import matplotlib.pylab as plt
import datetime
%matplotlib inline

from pandas.plotting import scatter_matrix
from statsmodels.stats.outliers_influence import variance_inflation_factor
from statsmodels.graphics.factorplots import interaction_plot
import statsmodels.stats.diagnostic as ssd
from statsmodels.stats.diagnostic import het_breuschpagan
from statsmodels.stats.diagnostic import het_goldfeldquandt

regression_df = pd.read_csv('data/for_regression.csv')
#regression_df.drop('Unnamed: 0', axis = 1, inplace = True)

In [2]:
regression_df.head()

,star_rating,helpful_votes,total_votes,vine,verified_purchase,review_date,review_word_count
0,4.0,3.0,4.0,0,1,2015-08-31,64
1,5.0,0.0,0.0,0,1,2015-08-31,3
2,3.0,0.0,0.0,0,1,2015-08-31,40
3,5.0,0.0,0.0,0,1,2015-08-31,12
4,2.0,0.0,1.0,0,1,2015-08-31,40

In [3]:
for i in range (len(regression_df)):
    date = regression_df.loc[i, 'review_date']
    if (len(str(date)) == 10):
        age = (2015 - int(date[0:4]))*365 + (8 - int(date[5:7]))*30.41
        regression_df.loc[i, 'days_old'] = age

regression_df.dropna(inplace = True)

In [4]:
regression_df.drop('review_date', axis = 1, inplace = True)

In [5]:
regression_df['helpfulness'] = 2*regression_df['helpful_votes']- regression_df['total_votes']

In [ ]:
regression_df = regression_df[regression_df[total_votes] != 0]

In [ ]:
regression_df.corr()

,star_rating,helpful_votes,total_votes,vine,verified_purchase,review_word_count,days_old,helpfulness
star_rating,1.000000,-0.047462,-0.070893,-0.037085,0.138136,-0.123895,-0.065620,-0.018880
helpful_votes,-0.047462,1.000000,0.990833,0.074666,-0.088067,0.221550,0.102613,0.987377
total_votes,-0.070893,0.990833,1.000000,0.080520,-0.097580,0.227422,0.113270,0.956929
vine,-0.037085,0.074666,0.080520,1.000000,-0.642150,0.468090,0.260006,0.066057
verified_purchase,0.138136,-0.088067,-0.097580,-0.642150,1.000000,-0.480968,-0.271383,-0.074856
review_word_count,-0.123895,0.221550,0.227422,0.468090,-0.480968,1.000000,0.274450,0.209487
days_old,-0.065620,0.102613,0.113270,0.260006,-0.271383,0.274450,1.000000,0.087721
helpfulness,-0.018880,0.987377,0.956929,0.066057,-0.074856,0.209487,0.087721,1.000000

In [ ]:
sns.pairplot(regression_df)

In [11]:
regression_df.corr()

,star_rating,helpful_ratio,vine,verified_purchase,review_word_count,days_old
star_rating,1.000000,0.086640,0.118919,0.012409,0.013503,0.020450
helpful_ratio,0.086640,1.000000,0.000656,-0.043024,0.120351,0.064251
vine,0.118919,0.000656,1.000000,-0.662279,0.390415,0.188008
verified_purchase,0.012409,-0.043024,-0.662279,1.000000,-0.408424,-0.241250
review_word_count,0.013503,0.120351,0.390415,-0.408424,1.000000,0.177063
days_old,0.020450,0.064251,0.188008,-0.241250,0.177063,1.000000